name: Update Friends

on:
  issues:
    types: [closed]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Generate Friends List
        run: python .github/workflows/update_friends.py
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit and Push
        run: |
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit. Exiting."
            exit 0
          fi

          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add friends.json
          git commit -m "Update friends.json via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
